name: Update badges

on:
  schedule:
    # Runs at 6th minute
    - cron: "6 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: cnsair/badge-readme@main
        with:       
          CREDLY_USER: samson-nwachukwu # optional, but default will use the same from github
